include:
  - project: 'trancport/blockchain/util/gitlab-ci-template'
    ref: main
    file: '/base.yml'

stages:
  - build

build-alpha:
  extends: .build
  variables:
    ENV: devnet.alpha
    GITLAB_TOKEN: $GITLAB_TOKEN
    IMAGE_TAG: $CI_COMMIT_TAG
    IMAGE_LATEST_TAG: latest
  only:
    - /^.*-alpha$/
  except:
    - branches

build-beta:
  extends: .build
  variables:
    ENV: devnet.beta
    GITLAB_TOKEN: $GITLAB_TOKEN
    IMAGE_TAG: $CI_COMMIT_TAG
    IMAGE_LATEST_TAG: latest
  only:
    - /^.*-beta$/
  except:
    - branches

build-prod:
  extends: .build
  variables:
    ENV: mainnet
    GITLAB_TOKEN: $GITLAB_TOKEN
    IMAGE_TAG: $CI_COMMIT_TAG
    IMAGE_LATEST_TAG: latest
  only:
    - /^.*-prod$/
  except:
    - branches