version: '3.8'
services:
  ashswap-monitor:
    image: ashswap-monitor
    ports:
      - 3001:3001
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
  local-redis: 
    image: redis:alpine
    ports:
      - 6379:6379
  