shards: 3
urls:
  api: ${ASHSWAP_NODE_APIS}
  gateway: ${ASHSWAP_NODE_GATEWAYS}
  statistic: ${STATISTIC_SERVICE}
redis:
  url: ${REDIS_URL}
  port: ${REDIS_PORT}
features:
  publicApi:
    enabled: ${API_ENABLED}
    port: ${PUBLIC_API_PORT}
  cron:
    enabled: ${CRON_ENABLED}
    port: ${CRON_PORT}
  keepAliveAgent:
    enabled: true
aggregate_pool:
  xexchange: ${XEXCHANGE_SERVICE_URL}
  ashswap: ${ASHSWAP_SERVICE_URL}
security:
  tokenSecret: ${TOKEN_SECRET}
  enable: ${SECURITY_ENABLED}
rateLimiterSecret:
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
useCachingInterceptor: false
sentryDsn: ${SENTRY_DSN}
